# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GroceRise
email: info@grocerise.com
description: > # this means to ignore newlines until "baseurl:"
  Save time spent in doing groceries and Rise affection with friends and neighbours
  with the new sharing lifestyle in GroceRise!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://grocerise.com" # the base hostname & protocol for your site
#twitter_username: hitchover
github_username:  linuxstudio/grocerise

# Build settings
markdown: kramdown
